name: Build and Push Docker Image

on:
  push:
    branches:
      [ main ]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            go install lesiw.io/op@latest

        - name: Log into Docker and upload image
          env: 
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            op build
