name: Build and Push Docker Image

on:
  push:
    branches:
      [ main ]
    paths:
      - dockerfile
  workflow_dispatch:

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        container: 
          image: hy0tic/common-runner-image
        steps:
        - name: Clone repo into subdirectory
          run: |
            git clone --depth=1 https://github.com/${{ github.repository }} repo
            cd repo
            git checkout ${{ github.ref_name }}
            ls -lah

        - name: Upload Docker Image to Docker Hub
          env: 
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            cd repo
            op buildandupload
