name: Export Workflow Data to SQS

on:
  workflow_run:
    workflows: ["Build Docker Image on PR", "Build and Push Docker Image"]
    types:
      - completed

jobs:
  send_metadata_to_sqs:
    runs-on: ubuntu-latest
    container:
      image: hy0tic/common-runner-image:latest
    steps:
      - name: Extract workflow run metadata
        run: |
          echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "run_started_at=${{ github.event.workflow_run.run_started_at }}" >> $GITHUB_OUTPUT
          echo "updated_at=${{ github.event.workflow_run.updated_at }}" >> $GITHUB_OUTPUT
          echo "status=${{ github.event.workflow_run.status }}" >> $GITHUB_OUTPUT
          echo "conclusion=${{ github.event.workflow_run.conclusion }}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Send metadata to AWS SQS
        run: |
          op exportdata
