name: Build Docker Image on PR

on:
  pull_request:
    branches:
      [ main ]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container: 
          image: hy0tic/common-runner-image
        steps:
        - name: Clone repo into subdirectory
          run: |
            git clone --depth=1 --branch ${{ github.event.pull_request.head.ref }} https://github.com/${{ github.repository }} repo
            cd repo
            ls -lah

        - name: test
          shell: bash
          run: |
            dotnet --version
            node --version
            npm --version
            python3 --version
            pip3 --version
            java -version