name: Build and Push Docker Image

on:
  pull_request:
    branches:
        [ main ]
    paths-ignore:
        - "**.md"
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container: 
          image: hy0tic/common-runner-image
        steps:
        - name: Clone repo into subdirectory
          run: |
            git clone --depth=1 --branch ${{ github.event.pull_request.head.ref }} https://github.com/${{ github.repository }} repo
            cd repo
            ls -lah

        - name: Build Docker image
          run: |
            cd repo
            ls -lah
            op build
